### ISSUE TITLE
Crash when opening GUI

### ISSUE THREAD

**Issue by LemADEC** [WingsOfLife/DynamicLiquidTanks_v2.0#18] opened 2014-01-21 01:18 UTC
I tried to place/remove controller, open/closing GUI and ended up with a client crash:

```
---- Minecraft Crash Report ----
// Shall we play a game?

Time: 21/01/14 02:05
Description: Exception in world tick

java.lang.NullPointerException
    at doc.mods.dynamictanks.client.gui.GuiController.func_73866_w_(GuiController.java:61)
    at net.minecraft.client.gui.GuiScreen.func_73872_a(SourceFile:94)
    at net.minecraft.client.gui.inventory.GuiContainer.func_73872_a(GuiContainer.java:99)
    at net.minecraft.client.Minecraft.func_71373_a(Minecraft.java:732)
    at cpw.mods.fml.client.FMLClientHandler.showGuiScreen(FMLClientHandler.java:398)
    at cpw.mods.fml.common.FMLCommonHandler.showGuiScreen(FMLCommonHandler.java:334)
    at cpw.mods.fml.common.network.NetworkRegistry.openLocalGui(NetworkRegistry.java:328)
    at cpw.mods.fml.common.network.FMLNetworkHandler.openGui(FMLNetworkHandler.java:357)
    at net.minecraft.entity.player.EntityPlayer.openGui(EntityPlayer.java:2480)
    at cpw.mods.fml.common.network.OpenGuiPacket.execute(OpenGuiPacket.java:67)
    at cpw.mods.fml.common.network.FMLNetworkHandler.handleFMLPacket(FMLNetworkHandler.java:116)
    at cpw.mods.fml.common.network.FMLNetworkHandler.handlePacket250Packet(FMLNetworkHandler.java:81)
    at net.minecraft.client.multiplayer.NetClientHandler.func_72501_a(NetClientHandler.java:1651)
    at net.minecraft.network.packet.Packet250CustomPayload.func_73279_a(SourceFile:61)
    at net.minecraft.network.TcpConnection.func_74428_b(TcpConnection.java:462)
    at net.minecraft.client.multiplayer.NetClientHandler.func_72551_d(NetClientHandler.java:281)
    at net.minecraft.client.multiplayer.WorldClient.func_72835_b(WorldClient.java:99)
    at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1930)
    at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:910)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:838)
    at net.minecraft.client.main.Main.main(SourceFile:101)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:131)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:27)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
    at doc.mods.dynamictanks.client.gui.GuiController.func_73866_w_(GuiController.java:61)
    at net.minecraft.client.gui.GuiScreen.func_73872_a(SourceFile:94)
    at net.minecraft.client.gui.inventory.GuiContainer.func_73872_a(GuiContainer.java:99)
    at net.minecraft.client.Minecraft.func_71373_a(Minecraft.java:732)
    at cpw.mods.fml.client.FMLClientHandler.showGuiScreen(FMLClientHandler.java:398)
    at cpw.mods.fml.common.FMLCommonHandler.showGuiScreen(FMLCommonHandler.java:334)
    at cpw.mods.fml.common.network.NetworkRegistry.openLocalGui(NetworkRegistry.java:328)
    at cpw.mods.fml.common.network.FMLNetworkHandler.openGui(FMLNetworkHandler.java:357)
    at net.minecraft.entity.player.EntityPlayer.openGui(EntityPlayer.java:2480)
    at cpw.mods.fml.common.network.OpenGuiPacket.execute(OpenGuiPacket.java:67)
    at cpw.mods.fml.common.network.FMLNetworkHandler.handleFMLPacket(FMLNetworkHandler.java:116)
    at cpw.mods.fml.common.network.FMLNetworkHandler.handlePacket250Packet(FMLNetworkHandler.java:81)
    at net.minecraft.client.multiplayer.NetClientHandler.func_72501_a(NetClientHandler.java:1651)
    at net.minecraft.network.packet.Packet250CustomPayload.func_73279_a(SourceFile:61)
    at net.minecraft.network.TcpConnection.func_74428_b(TcpConnection.java:462)
    at net.minecraft.client.multiplayer.NetClientHandler.func_72551_d(NetClientHandler.java:281)

-- Affected level --
Details:
    Level name: MpServer
    All players: 1 total; [GCCorePlayerSP['LemADEC'/29656, l='MpServer', x=260,09, y=74,55, z=384,20]]
    Chunk stats: MultiplayerChunkCache: 441
    Level seed: 0
    Level generator: ID 04 - BIOMESOP, ver 0. Features enabled: false
    Level generator options: 
    Level spawn location: World: (265,73,405), Chunk: (at 9,4,5 in 16,25; contains blocks 256,0,400 to 271,255,415), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
    Level time: 17397359 game time, 10442803 day time
    Level dimension: 0
    Level storage version: 0x00000 - Unknown?
    Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
    Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
    Forced entities: 50 total; [EntityTFNagaSegment['unknown'/3167, l='MpServer', x=0,00, y=0,00, z=0,00], EntityTFNagaSegment['unknown'/3166, l='MpServer', x=0,00, y=0,00, z=0,00], EntityBlock['unknown'/2985, l='MpServer', x=243,25, y=62,00, z=389,25], GCCorePlayerSP['LemADEC'/29656, l='MpServer', x=260,09, y=74,55, z=384,20], EntityHat['unknown'/3403, l='MpServer', x=260,09, y=74,55, z=384,13], EntityHat['unknown'/3400, l='MpServer', x=260,06, y=74,55, z=383,86], EntityHat['unknown'/2986, l='MpServer', x=261,29, y=74,55, z=382,13], EntityHat['unknown'/3394, l='MpServer', x=259,80, y=74,55, z=382,61], EntityHat['unknown'/3395, l='MpServer', x=259,88, y=74,55, z=383,05], EntityHat['unknown'/3421, l='MpServer', x=260,09, y=74,55, z=384,20], EntityHat['unknown'/3420, l='MpServer', x=260,09, y=74,55, z=384,20], EntityHat['unknown'/3417, l='MpServer', x=260,09, y=74,55, z=384,20], EntityHat['unknown'/3412, l='MpServer', x=260,09, y=74,55, z=384,20], EntityHat['unknown'/3433, l='MpServer', x=260,09, y=74,55, z=384,20], EntityHat['unknown'/3326, l='MpServer', x=261,29, y=74,55, z=382,13], EntityHat['unknown'/3424, l='MpServer', x=260,09, y=74,55, z=384,20], EntityTFNagaSegment['unknown'/3176, l='MpServer', x=0,00, y=0,00, z=0,00], EntityHat['unknown'/3451, l='MpServer', x=260,09, y=74,55, z=384,20], EntityTFNagaSegment['unknown'/3177, l='MpServer', x=0,00, y=0,00, z=0,00], EntityTFNagaSegment['unknown'/3174, l='MpServer', x=0,00, y=0,00, z=0,00], EntityHat['unknown'/3445, l='MpServer', x=260,09, y=74,55, z=384,20], EntityTFNagaSegment['unknown'/3175, l='MpServer', x=0,00, y=0,00, z=0,00], EntityTFNagaSegment['unknown'/3172, l='MpServer', x=0,00, y=0,00, z=0,00], EntityTFNagaSegment['unknown'/3173, l='MpServer', x=0,00, y=0,00, z=0,00], EntityHat['unknown'/3446, l='MpServer', x=260,09, y=74,55, z=384,20], EntityTFNagaSegment['unknown'/3170, l='MpServer', x=0,00, y=0,00, z=0,00], EntityTFNagaSegment['unknown'/3171, l='MpServer', x=0,00, y=0,00, z=0,00], EntityHat['unknown'/3440, l='MpServer', x=260,09, y=74,55, z=384,20], EntityTFNagaSegment['unknown'/3168, l='MpServer', x=0,00, y=0,00, z=0,00], EntityTFNagaSegment['unknown'/3169, l='MpServer', x=0,00, y=0,00, z=0,00], EntityHat['unknown'/3456, l='MpServer', x=260,09, y=74,55, z=384,20], EntityHat['unknown'/3342, l='MpServer', x=260,27, y=74,55, z=380,27], EntityHat['unknown'/3331, l='MpServer', x=261,26, y=74,55, z=381,87], EntityHat['unknown'/3225, l='MpServer', x=261,29, y=74,55, z=382,13], EntityHat['unknown'/3465, l='MpServer', x=260,09, y=74,55, z=384,20], EntityHat['unknown'/3471, l='MpServer', x=260,09, y=74,55, z=384,20], EntityZombie['Zombie'/3230, l='MpServer', x=0,91, y=-33,55, z=43,80], EntityHat['unknown'/3468, l='MpServer', x=260,09, y=74,55, z=384,20], EntityHat['unknown'/3353, l='MpServer', x=259,91, y=74,55, z=379,71], EntityHat['unknown'/3482, l='MpServer', x=260,09, y=74,55, z=384,20], EntityHat['unknown'/3489, l='MpServer', x=260,09, y=74,55, z=384,20], EntityHat['unknown'/3250, l='MpServer', x=261,29, y=74,55, z=382,13], EntityHat['unknown'/3494, l='MpServer', x=260,09, y=74,55, z=384,20], EntityHat['unknown'/3364, l='MpServer', x=259,80, y=74,55, z=379,53], EntityHat['unknown'/3235, l='MpServer', x=261,29, y=74,55, z=382,13], EntityHat['unknown'/3391, l='MpServer', x=259,80, y=74,55, z=382,38], EntityHat['unknown'/3377, l='MpServer', x=259,80, y=74,55, z=380,53], EntityHat['unknown'/3240, l='MpServer', x=261,29, y=74,55, z=382,13], EntityHat['unknown'/3247, l='MpServer', x=261,29, y=74,55, z=382,13], EntityHat['unknown'/3380, l='MpServer', x=259,80, y=74,55, z=381,69]]
    Retry entities: 49 total; [EntityTFNagaSegment['unknown'/3167, l='MpServer', x=0,00, y=0,00, z=0,00], EntityHat['unknown'/3456, l='MpServer', x=260,09, y=74,55, z=384,20], EntityTFNagaSegment['unknown'/3166, l='MpServer', x=0,00, y=0,00, z=0,00], EntityBlock['unknown'/2985, l='MpServer', x=243,25, y=62,00, z=389,25], EntityHat['unknown'/3342, l='MpServer', x=260,27, y=74,55, z=380,27], EntityHat['unknown'/3403, l='MpServer', x=260,09, y=74,55, z=384,13], EntityHat['unknown'/3400, l='MpServer', x=260,06, y=74,55, z=383,86], EntityHat['unknown'/2986, l='MpServer', x=261,29, y=74,55, z=382,13], EntityHat['unknown'/3225, l='MpServer', x=261,29, y=74,55, z=382,13], EntityHat['unknown'/3331, l='MpServer', x=261,26, y=74,55, z=381,87], EntityHat['unknown'/3465, l='MpServer', x=260,09, y=74,55, z=384,20], EntityHat['unknown'/3471, l='MpServer', x=260,09, y=74,55, z=384,20], EntityHat['unknown'/3394, l='MpServer', x=259,80, y=74,55, z=382,61], EntityHat['unknown'/3395, l='MpServer', x=259,88, y=74,55, z=383,05], EntityZombie['Zombie'/3230, l='MpServer', x=0,91, y=-33,55, z=43,80], EntityHat['unknown'/3468, l='MpServer', x=260,09, y=74,55, z=384,20], EntityHat['unknown'/3421, l='MpServer', x=260,09, y=74,55, z=384,20], EntityHat['unknown'/3353, l='MpServer', x=259,91, y=74,55, z=379,71], EntityHat['unknown'/3420, l='MpServer', x=260,09, y=74,55, z=384,20], EntityHat['unknown'/3417, l='MpServer', x=260,09, y=74,55, z=384,20], EntityHat['unknown'/3482, l='MpServer', x=260,09, y=74,55, z=384,20], EntityHat['unknown'/3412, l='MpServer', x=260,09, y=74,55, z=384,20], EntityHat['unknown'/3489, l='MpServer', x=260,09, y=74,55, z=384,20], EntityHat['unknown'/3250, l='MpServer', x=261,29, y=74,55, z=382,13], EntityHat['unknown'/3433, l='MpServer', x=260,09, y=74,55, z=384,20], EntityHat['unknown'/3494, l='MpServer', x=260,09, y=74,55, z=384,20], EntityHat['unknown'/3326, l='MpServer', x=261,29, y=74,55, z=382,13], EntityHat['unknown'/3424, l='MpServer', x=260,09, y=74,55, z=384,20], EntityHat['unknown'/3364, l='MpServer', x=259,80, y=74,55, z=379,53], EntityHat['unknown'/3235, l='MpServer', x=261,29, y=74,55, z=382,13], EntityHat['unknown'/3451, l='MpServer', x=260,09, y=74,55, z=384,20], EntityHat['unknown'/3391, l='MpServer', x=259,80, y=74,55, z=382,38], EntityTFNagaSegment['unknown'/3176, l='MpServer', x=0,00, y=0,00, z=0,00], EntityTFNagaSegment['unknown'/3177, l='MpServer', x=0,00, y=0,00, z=0,00], EntityHat['unknown'/3445, l='MpServer', x=260,09, y=74,55, z=384,20], EntityHat['unknown'/3377, l='MpServer', x=259,80, y=74,55, z=380,53], EntityTFNagaSegment['unknown'/3174, l='MpServer', x=0,00, y=0,00, z=0,00], EntityTFNagaSegment['unknown'/3175, l='MpServer', x=0,00, y=0,00, z=0,00], EntityTFNagaSegment['unknown'/3172, l='MpServer', x=0,00, y=0,00, z=0,00], EntityHat['unknown'/3446, l='MpServer', x=260,09, y=74,55, z=384,20], EntityTFNagaSegment['unknown'/3173, l='MpServer', x=0,00, y=0,00, z=0,00], EntityHat['unknown'/3240, l='MpServer', x=261,29, y=74,55, z=382,13], EntityTFNagaSegment['unknown'/3170, l='MpServer', x=0,00, y=0,00, z=0,00], EntityHat['unknown'/3247, l='MpServer', x=261,29, y=74,55, z=382,13], EntityHat['unknown'/3440, l='MpServer', x=260,09, y=74,55, z=384,20], EntityHat['unknown'/3380, l='MpServer', x=259,80, y=74,55, z=381,69], EntityTFNagaSegment['unknown'/3171, l='MpServer', x=0,00, y=0,00, z=0,00], EntityTFNagaSegment['unknown'/3168, l='MpServer', x=0,00, y=0,00, z=0,00], EntityTFNagaSegment['unknown'/3169, l='MpServer', x=0,00, y=0,00, z=0,00]]
    Server brand: mcpc,craftbukkit,fml,forge
    Server type: Non-integrated multiplayer server
Stacktrace:
    at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:440)
    at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1943)
    at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:910)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:838)
    at net.minecraft.client.main.Main.main(SourceFile:101)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:131)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:27)

-- Affected level --
Details:
    Level name: MpServer
    All players: 1 total; [GCCorePlayerSP['LemADEC'/29656, l='MpServer', x=260,09, y=74,55, z=384,20]]
    Chunk stats: MultiplayerChunkCache: 441
    Level seed: 0
    Level generator: ID 04 - BIOMESOP, ver 0. Features enabled: false
    Level generator options: 
    Level spawn location: World: (265,73,405), Chunk: (at 9,4,5 in 16,25; contains blocks 256,0,400 to 271,255,415), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
    Level time: 17397359 game time, 10442803 day time
    Level dimension: 0
    Level storage version: 0x00000 - Unknown?
    Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
    Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
    Forced entities: 50 total; [EntityTFNagaSegment['unknown'/3167, l='MpServer', x=0,00, y=0,00, z=0,00], EntityTFNagaSegment['unknown'/3166, l='MpServer', x=0,00, y=0,00, z=0,00], EntityBlock['unknown'/2985, l='MpServer', x=243,25, y=62,00, z=389,25], GCCorePlayerSP['LemADEC'/29656, l='MpServer', x=260,09, y=74,55, z=384,20], EntityHat['unknown'/3403, l='MpServer', x=260,09, y=74,55, z=384,13], EntityHat['unknown'/3400, l='MpServer', x=260,06, y=74,55, z=383,86], EntityHat['unknown'/2986, l='MpServer', x=261,29, y=74,55, z=382,13], EntityHat['unknown'/3394, l='MpServer', x=259,80, y=74,55, z=382,61], EntityHat['unknown'/3395, l='MpServer', x=259,88, y=74,55, z=383,05], EntityHat['unknown'/3421, l='MpServer', x=260,09, y=74,55, z=384,20], EntityHat['unknown'/3420, l='MpServer', x=260,09, y=74,55, z=384,20], EntityHat['unknown'/3417, l='MpServer', x=260,09, y=74,55, z=384,20], EntityHat['unknown'/3412, l='MpServer', x=260,09, y=74,55, z=384,20], EntityHat['unknown'/3433, l='MpServer', x=260,09, y=74,55, z=384,20], EntityHat['unknown'/3326, l='MpServer', x=261,29, y=74,55, z=382,13], EntityHat['unknown'/3424, l='MpServer', x=260,09, y=74,55, z=384,20], EntityTFNagaSegment['unknown'/3176, l='MpServer', x=0,00, y=0,00, z=0,00], EntityHat['unknown'/3451, l='MpServer', x=260,09, y=74,55, z=384,20], EntityTFNagaSegment['unknown'/3177, l='MpServer', x=0,00, y=0,00, z=0,00], EntityTFNagaSegment['unknown'/3174, l='MpServer', x=0,00, y=0,00, z=0,00], EntityHat['unknown'/3445, l='MpServer', x=260,09, y=74,55, z=384,20], EntityTFNagaSegment['unknown'/3175, l='MpServer', x=0,00, y=0,00, z=0,00], EntityTFNagaSegment['unknown'/3172, l='MpServer', x=0,00, y=0,00, z=0,00], EntityTFNagaSegment['unknown'/3173, l='MpServer', x=0,00, y=0,00, z=0,00], EntityHat['unknown'/3446, l='MpServer', x=260,09, y=74,55, z=384,20], EntityTFNagaSegment['unknown'/3170, l='MpServer', x=0,00, y=0,00, z=0,00], EntityTFNagaSegment['unknown'/3171, l='MpServer', x=0,00, y=0,00, z=0,00], EntityHat['unknown'/3440, l='MpServer', x=260,09, y=74,55, z=384,20], EntityTFNagaSegment['unknown'/3168, l='MpServer', x=0,00, y=0,00, z=0,00], EntityTFNagaSegment['unknown'/3169, l='MpServer', x=0,00, y=0,00, z=0,00], EntityHat['unknown'/3456, l='MpServer', x=260,09, y=74,55, z=384,20], EntityHat['unknown'/3342, l='MpServer', x=260,27, y=74,55, z=380,27], EntityHat['unknown'/3331, l='MpServer', x=261,26, y=74,55, z=381,87], EntityHat['unknown'/3225, l='MpServer', x=261,29, y=74,55, z=382,13], EntityHat['unknown'/3465, l='MpServer', x=260,09, y=74,55, z=384,20], EntityHat['unknown'/3471, l='MpServer', x=260,09, y=74,55, z=384,20], EntityZombie['Zombie'/3230, l='MpServer', x=0,91, y=-33,55, z=43,80], EntityHat['unknown'/3468, l='MpServer', x=260,09, y=74,55, z=384,20], EntityHat['unknown'/3353, l='MpServer', x=259,91, y=74,55, z=379,71], EntityHat['unknown'/3482, l='MpServer', x=260,09, y=74,55, z=384,20], EntityHat['unknown'/3489, l='MpServer', x=260,09, y=74,55, z=384,20], EntityHat['unknown'/3250, l='MpServer', x=261,29, y=74,55, z=382,13], EntityHat['unknown'/3494, l='MpServer', x=260,09, y=74,55, z=384,20], EntityHat['unknown'/3364, l='MpServer', x=259,80, y=74,55, z=379,53], EntityHat['unknown'/3235, l='MpServer', x=261,29, y=74,55, z=382,13], EntityHat['unknown'/3391, l='MpServer', x=259,80, y=74,55, z=382,38], EntityHat['unknown'/3377, l='MpServer', x=259,80, y=74,55, z=380,53], EntityHat['unknown'/3240, l='MpServer', x=261,29, y=74,55, z=382,13], EntityHat['unknown'/3247, l='MpServer', x=261,29, y=74,55, z=382,13], EntityHat['unknown'/3380, l='MpServer', x=259,80, y=74,55, z=381,69]]
    Retry entities: 49 total; [EntityTFNagaSegment['unknown'/3167, l='MpServer', x=0,00, y=0,00, z=0,00], EntityHat['unknown'/3456, l='MpServer', x=260,09, y=74,55, z=384,20], EntityTFNagaSegment['unknown'/3166, l='MpServer', x=0,00, y=0,00, z=0,00], EntityBlock['unknown'/2985, l='MpServer', x=243,25, y=62,00, z=389,25], EntityHat['unknown'/3342, l='MpServer', x=260,27, y=74,55, z=380,27], EntityHat['unknown'/3403, l='MpServer', x=260,09, y=74,55, z=384,13], EntityHat['unknown'/3400, l='MpServer', x=260,06, y=74,55, z=383,86], EntityHat['unknown'/2986, l='MpServer', x=261,29, y=74,55, z=382,13], EntityHat['unknown'/3225, l='MpServer', x=261,29, y=74,55, z=382,13], EntityHat['unknown'/3331, l='MpServer', x=261,26, y=74,55, z=381,87], EntityHat['unknown'/3465, l='MpServer', x=260,09, y=74,55, z=384,20], EntityHat['unknown'/3471, l='MpServer', x=260,09, y=74,55, z=384,20], EntityHat['unknown'/3394, l='MpServer', x=259,80, y=74,55, z=382,61], EntityHat['unknown'/3395, l='MpServer', x=259,88, y=74,55, z=383,05], EntityZombie['Zombie'/3230, l='MpServer', x=0,91, y=-33,55, z=43,80], EntityHat['unknown'/3468, l='MpServer', x=260,09, y=74,55, z=384,20], EntityHat['unknown'/3421, l='MpServer', x=260,09, y=74,55, z=384,20], EntityHat['unknown'/3353, l='MpServer', x=259,91, y=74,55, z=379,71], EntityHat['unknown'/3420, l='MpServer', x=260,09, y=74,55, z=384,20], EntityHat['unknown'/3417, l='MpServer', x=260,09, y=74,55, z=384,20], EntityHat['unknown'/3482, l='MpServer', x=260,09, y=74,55, z=384,20], EntityHat['unknown'/3412, l='MpServer', x=260,09, y=74,55, z=384,20], EntityHat['unknown'/3489, l='MpServer', x=260,09, y=74,55, z=384,20], EntityHat['unknown'/3250, l='MpServer', x=261,29, y=74,55, z=382,13], EntityHat['unknown'/3433, l='MpServer', x=260,09, y=74,55, z=384,20], EntityHat['unknown'/3494, l='MpServer', x=260,09, y=74,55, z=384,20], EntityHat['unknown'/3326, l='MpServer', x=261,29, y=74,55, z=382,13], EntityHat['unknown'/3424, l='MpServer', x=260,09, y=74,55, z=384,20], EntityHat['unknown'/3364, l='MpServer', x=259,80, y=74,55, z=379,53], EntityHat['unknown'/3235, l='MpServer', x=261,29, y=74,55, z=382,13], EntityHat['unknown'/3451, l='MpServer', x=260,09, y=74,55, z=384,20], EntityHat['unknown'/3391, l='MpServer', x=259,80, y=74,55, z=382,38], EntityTFNagaSegment['unknown'/3176, l='MpServer', x=0,00, y=0,00, z=0,00], EntityTFNagaSegment['unknown'/3177, l='MpServer', x=0,00, y=0,00, z=0,00], EntityHat['unknown'/3445, l='MpServer', x=260,09, y=74,55, z=384,20], EntityHat['unknown'/3377, l='MpServer', x=259,80, y=74,55, z=380,53], EntityTFNagaSegment['unknown'/3174, l='MpServer', x=0,00, y=0,00, z=0,00], EntityTFNagaSegment['unknown'/3175, l='MpServer', x=0,00, y=0,00, z=0,00], EntityTFNagaSegment['unknown'/3172, l='MpServer', x=0,00, y=0,00, z=0,00], EntityHat['unknown'/3446, l='MpServer', x=260,09, y=74,55, z=384,20], EntityTFNagaSegment['unknown'/3173, l='MpServer', x=0,00, y=0,00, z=0,00], EntityHat['unknown'/3240, l='MpServer', x=261,29, y=74,55, z=382,13], EntityTFNagaSegment['unknown'/3170, l='MpServer', x=0,00, y=0,00, z=0,00], EntityHat['unknown'/3247, l='MpServer', x=261,29, y=74,55, z=382,13], EntityHat['unknown'/3440, l='MpServer', x=260,09, y=74,55, z=384,20], EntityHat['unknown'/3380, l='MpServer', x=259,80, y=74,55, z=381,69], EntityTFNagaSegment['unknown'/3171, l='MpServer', x=0,00, y=0,00, z=0,00], EntityTFNagaSegment['unknown'/3168, l='MpServer', x=0,00, y=0,00, z=0,00], EntityTFNagaSegment['unknown'/3169, l='MpServer', x=0,00, y=0,00, z=0,00]]
    Server brand: mcpc,craftbukkit,fml,forge
    Server type: Non-integrated multiplayer server

-- System Details --
Details:
    Minecraft Version: 1.6.4
    Operating System: Windows 7 (amd64) version 6.1
    Java Version: 1.7.0_51, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 201685600 bytes (192 MB) / 1712848896 bytes (1633 MB) up to 2863661056 bytes (2731 MB)
    JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx3072m -XX:MaxPermSize=256m
    AABB Pool Size: 24231 (1356936 bytes; 1 MB) allocated, 15 (840 bytes; 0 MB) used
    Suspicious classes: FML and Forge are installed
    IntCache: cache: 1, tcache: 358, allocated: 4, tallocated: 58
    FML: MCP v8.11 FML v6.4.49.965 Minecraft Forge 9.11.1.965 179 mods loaded, 179 mods active
    mcp{8.09} [Minecraft Coder Pack] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    FML{6.4.49.965} [Forge Mod Loader] (modpack.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    Forge{9.11.1.965} [Minecraft Forge] (modpack.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
...
```

**Comment by WingsOfLife** [comment] 2014-01-21 16:03
Duplicate of #17 fixed in next release.

**Closed as completed by WingsOfLife** 2014-01-21 16:03 UTC
Labels: duplicate
